### ISSUE TITLE
Make the modal scrollable

### ISSUE THREAD

**Issue by maximelafarie** [biig-io/ngx-smart-modal#10]
If the content of the modal is big and its height is greater than the height of the screen / browser, the modal extends the main height, event if the body's height is limited and/or defined  e.g.: 
```
body { height: 100%; }
```
At the beginning the modal has a normal behavior:
![image](https://user-images.githubusercontent.com/5319267/28753437-d294bee2-7534-11e7-9abe-f044bdf93d2a.png)

But at scroll time, the whole page is scrolling, not only the modal (and this is what we want !):
![image](https://user-images.githubusercontent.com/5319267/28753482-149a7f02-7535-11e7-8a6e-03aa7057416d.png)

**Comment by maximelafarie** [comment]
@Del-Toon need informations about the effort needed for this issue. What's your estimation about that?

**Comment by Del-Toon** [comment]
I have to look at the markup, but I think that it is that a case of `position` and possibly of a parent container to be created.

I have it for less than one hour!

**Comment by maximelafarie** [comment]
@Del-Toon Awesome! Yes, it needs to be totally independent of its parent. E.g.: a modal directly in the `<body></body>` or a modal in a modal (nested markup) e.g:
```
<!-- MODAL ONE -->
<ngx-smart-modal #firstModal [identifier]="'firstModal'">
  <h1>Parent Modal</h1>
  <p>Some stuff...</p>

  <button (click)="firstModal.close()">Close</button>
  <button (click)="secondModal.close()">Open secondModal</button>

  <!-- MODAL TWO -->
  <ngx-smart-modal #secondModal [identifier]="'secondModal'">
    <h1>Child modal</h1>
    <p>...Looooong content...</p>
  
    <button (click)="secondModal.close()">Close</button>
  </ngx-smart-modal>
</ngx-smart-modal>
```

 So regardless of its container, a modal **should** be scrollable.

**Comment by maximelafarie** [comment]
Thank you @marco10024 and @Del-Toon 👍
