### ISSUE TITLE
cannot set the custom style for the modal

### ISSUE THREAD

**Issue by mkamrani** [biig-io/ngx-smart-modal#101]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[ ] feature request
[x ] support request
```
Hi and thank you for your useful component,
My problem is that I need to set the modal width to say 90% but it seems that the styles are not applied to the element. In fact if I set this style directly on the element (inspecting it in Chrome), it works, but not when I just use the styles in the code.

```
  <ngx-smart-modal #createModal [identifier]="'createModal'" [customClass]="'wide-modal'">
    <app-create-role *ngIf="showCreate" (done)="createDone()"></app-create-role>
  </ngx-smart-modal>
```
style:

```
.wide-modal {
  min-width: 900px;
  background-color: blue; // Just to confirm that no style is being applied, irrespective of the parent, etc.
  
}
```

**Comment by maximelafarie** [comment]
Hi @mkamrani and thank you for the kind words! 😀 

Which version of `ngx-smart-modal` are you currently using?

**Comment by mkamrani** [comment]
@maximelafarie I'm using version 5.0.0

**Comment by maximelafarie** [comment]
@mkamrani I suggest you to follow this example: https://github.com/biig-io/ngx-smart-modal/blob/e461bf98815a10fb5c875856298cc0da46810546/src/app/app.component.scss#L64#L65#L66

```
.large-modal {
  max-width: none !important;
}
```

You can check the result in the demo with the "inception modal" button.

To avoid using `!important` to apply desired styles, I suggest you to upgrade to version `6.0.0`, style are now so easy to override 😉 

Tell me if it helps you! 🖖

**Comment by mkamrani** [comment]
Thanks for surprisingly prompt response!
Actually before that I should check why after updating the package to version it's no long working! Actually the content of the modals are being rendered as if the modal is like a simple div element at the bottom of the page. 

Perhaps cleaning the packages and installing them again may help.

**Comment by maximelafarie** [comment]
@mkamrani You're right, there's some breaking changes while upgrading to `6.0.0`. You need to import the dedicated `style.css` / `style.scss` file in order to get the default modal style. Then you simply have to do some style and apply class to desired modal. 😄

**Comment by mkamrani** [comment]
Alright I fixed the issue as per your advise. Just I want to add two points:

1- I think you need to add the reference to the style file like this:
@import "~ngx-smart-modal/ngx-smart-modal"; // please note the ~
This can perhaps be reflected in the documentation as well.

2- Wouldn't it be better if the width and height be exposed as variables as well?
I'm happy to do that with a PR, though it's very trivial.

Thanks again.

**Comment by maximelafarie** [comment]
Excellent @mkamrani! 👌 

To answer your questions as clearly as possible:

1. If it is for the demo, it's not possible given that the library is inside the demo, so the path is not the same as it would be with a classic NPM installation of `ngx-smart-modal`. I precise it in the **[dedicated part of the documentation](https://github.com/biig-io/ngx-smart-modal#style--customization)**. 😉 

2. Yes, it would be very useful and pertinent! Feel free to make a PR! 👍 

My pleasure, thank you for your feedback!
