### ISSUE TITLE
Request component input to assign modal relative parent

### ISSUE THREAD

**Issue by StewartJingga** [biig-io/ngx-smart-modal#102]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

I'm using a left sidebar menu in my angular app. The ngx-smart-modal component is instantiated in my main content area which is on the right side of the screen because the sidebar is on the left side. The problem is when I open the modal, it center itself relative to the main content screen which I completely understand why.  

**Expected behavior**

I would love a feature where I can assign where the modal is relative to (e.g "body") so it can center itself according to my needs.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Smart Modal version:** 6.0.0

* **Angular version:** 5.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by maximelafarie** [comment]
Hi @StewartJingga, thank you for submitting this feature request.
I will discuss about this with the dev core team in order to estimate the effort of such a feature.

In all cases, it's an interesting feature. 👍 

Stay tuned about the progress of this feature on this issue, I'll gradually update it.

**Comment by khylias** [comment]
Hi @StewartJingga, @maximelafarie,

I'll investigate about this feature request. At first look, the referal parent is subject about CSS rules and we can't overwrite your own component's stylesheet. But you can set the parent container's position at `static` and body's position at `relative`.

Let me know if this works.

Best regards 🙌

**Comment by maximelafarie** [comment]
You can play with your modal style and add a `position: fixed;` rule to it. Thus, it will be relative to the viewport (and then your body).

In any cases, PRs are welcome! 🖖
