### ISSUE TITLE
When [closeable]="true" clicking the close button causes the parent form to submit

### ISSUE THREAD

**Issue by ajay987s** [biig-io/ngx-smart-modal#104]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Clicking the X close button top right when [closeable]="true" causes the form on the parent page to submit. If this is implemented as a button then it needs type="button" as the default type is a submit button.

**Expected behavior**
The dialog should just close without submitting the parent form.

**Reproduction of the problem**
Invoke the dialog from a page with a form that is active. Click the X button. The parent form submits.

**What is the motivation / use case for changing the behavior?**
Unintended side effects,

**Please tell us about your environment:**
Angular 5 cli

* **Smart Modal version:** 
6.0.0

* **Angular version:** 
5.2.0

* **Browser:** 
Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Firefox 59.0.2 64 Bit

* **Language:** 
Typescript

**Comment by khylias** [comment]
hi @ajay987s , 

thank you for reporting this bug. Indeed, it'll be better as an type button.
In waiting of an update, you can set your own closeable button in your modal, which use closing method of our modal service. 

Feel free to make PR and contribute at NgxSmartModal 🤘

**Comment by maximelafarie** [comment]
Hi @ajay987s, @khylias!

I'm currently working on a patch release to fix some other issues / bugs. I'll include this one into it.

Thanks for reporting it,

Happy coding! 🖖
