### ISSUE TITLE
visible field doesnt work

### ISSUE THREAD

**Issue by therepo90** [biig-io/ngx-smart-modal#108]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
visible attr is not taken into account
**Expected behavior**
visible attr should be taken into account

**Reproduction of the problem**
Add [visible]="true" and see if it shows up

**What is the motivation / use case for changing the behavior?**
I dont know

**Please tell us about your environment:**
not important

* **Smart Modal version:** 0.8.x
latest

* **Angular version:** 2.0.x
ang 5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by khylias** [comment]
Hi @therepo90,

Thanks for your interest in Ngx-Smart-Modal, indeed there is a bug concerning the visible modal attribute. We'll take some time to fix it. 
You are free to participate in the project by contributing with a pull request 🤟

**Comment by maximelafarie** [comment]
Hi all! I'm currently working on a fix branch to fix current issues. I add this one to the list.

Stay tuned! 🖖

**Comment by maximelafarie** [comment]
Hi @lkostrowski, I'm refactoring / fixing some stuff in the library and I would like to know if you've done something about this issue. I'm testing several ways to fix that, as this thread shows: https://stackoverflow.com/questions/38571812/how-to-detect-when-an-input-value-changes-in-angular . 

Let me know if you have any suggestion or in-progress work. 😉 

Cheers 🖖

**Comment by lkostrowski** [comment]
Hi

Sorry, haven't had time for that and we basically implemented our own modal.

I'm working now on refactoring it and I think about making it kind of "controlled component", which will only receive view-related inputs and visible: true/false. 
It could emit events which will be taken by some global service for communication (showing overlay and other actions). Anyway - modal will be stateless and controller will be moved to parent component

**Comment by maximelafarie** [comment]
As said in the description by @therepo90 and after thinking about it, there's no need to make `visible` an `@Input`. The service support this job and opening/closing a modal could be done directly with the built-in methods.

It seems `[visible]` options is not used and does not offer a useful service for users. Toggling the visibility of a modal could be done with modal built-in `toggle()` method or with the service.

To avoid breaks, it will stay as an option until the next major release, but it will be undocumented in the next release.
