### ISSUE TITLE
npm version is wrong

### ISSUE THREAD

**Issue by JafarAmini** [biig-io/ngx-smart-modal#112]
npm version is wrong and version is 6.0.3 and does not work at all

**Comment by khylias** [comment]
I just tested version 6.0.2 released on npm. This version works.
The trouble you encountered didn't come from our component.
If you encounter other bugs, you can post another issue or contact us on[ Gitter](https://gitter.im/ngx-smart-modal/Lobby) for quick question with quick answers.
