### ISSUE TITLE
Error when performing AOT build: Property 'escapeKeyboardEvent' is private

### ISSUE THREAD

**Issue by matthewdunsdon** [biig-io/ngx-smart-modal#115]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

When performing an AOT build, I get the following error.

```shell
ERROR in (1,1): : Directive NgxSmartModalComponent, Property 'escapeKeyboardEvent' is private and only accessible within class 'NgxSmartModalComponent'.
ClientApp\app\public\productdetails\productdetails.component.html(56,1): : Directive NgxSmartModalComponent, Property 'escapeKeyboardEvent' is private and only accessible within class 'NgxSmartModalComponent'.
```

**Expected behavior**

I was expecting to be able to do AOT build.

**Reproduction of the problem**

Content of component HTML template
```html
<!-- ... -->
<ngx-smart-modal #classicModal identifier="classicModal">
  <h1>Hey, I'm a simple modal!</h1>
  <img class="modal-image" src="http://lorempicsum.com/futurama/627/200/3" alt="Lorem picsum">
  <p>{{ "sampleText[0]" }}</p>
  <button class="button -dark" (click)="classicModal.close()">Close</button>
</ngx-smart-modal>
```

Content of app module

```js
  // ...
  imports: [
    BrowserModule,
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    NgxSmartModalModule.forRoot(),
    // ....
  ]
  // ...
```

**Please tell us about your environment:**

* Windows 10 Enterprise

* **Smart Modal version:** 6.0.2

* **Angular version:** 5.2.10

* **Browser:** N/A

* **Language:** TypeScript 2.5.3

**Comment by maximelafarie** [comment]
Hi @matthewdunsdon! Are you trying to access `escapeKeyboardEvent` in your template? (line no.56)

Are you importing `NgxSmartModalModule.forRoot()` in a nested module?

@khylias Be careful, the demo builds well on CI as you can see [here](https://travis-ci.org/biig-io/ngx-smart-modal/jobs/384393926#L1161). If the problem is not client-side, it's maybe a library compilation error. I'll watch potential fixes from https://github.com/robisim74/angular-library-starter.

**Comment by matthewdunsdon** [comment]
> Are you trying to access escapeKeyboardEvent in your template?

No.

Are you importing NgxSmartModalModule.forRoot() in a nested module?

No.

**Comment by matthewdunsdon** [comment]
In [`ngx-smart-modal.component.ts#L183-L184`](https://github.com/biig-io/ngx-smart-modal/blob/8249c8853fc25f7eb03fde6568cd0eb36d0dd461/src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts#L183-L184), I see the following:

```js
  @HostListener('document:keyup', ['$event'])
  private escapeKeyboardEvent(event: KeyboardEvent) {
```

Question to consider ...

* Is is valid to use a `@HostListener` annotation on a private method?

Angular AOT does care check whether fields / properties /methods are private, both when checking html templates and on component usage (i.e. by library consumers like myself 🗣 ).

**Comment by maximelafarie** [comment]
Yep, you're right @matthewdunsdon, I'll fix that! 👌
