### ISSUE TITLE
ngx-smart-modal parameters are not working in angular5

### ISSUE THREAD

**Issue by titto-xavier** [biig-io/ngx-smart-modal#117]
I am using 'ngx-smart-modal' version of 3.1.0 in my angular5 app with the help of [this link](https://www.npmjs.com/package/ngx-smart-modal) .When I given the default parameters mentioned in the official tutorial it's not working.

`<ngx-smart-modal #myModal identifier="myModal" dismissable="false">
   <p>hello</p>
 </ngx-smart-modal>`

in the above code I trying to give the dismissable parameter as false for preventing the closing of modal when clicking on backdrop,but it's not working.How can I pass these parameters in ngx-smart-modal ?

**Comment by maximelafarie** [comment]
By using `dismissable="false"` you are passing the **string** value of `false`. To pass a `boolean` value to the component, you must use this options like that: `[dismissable]="false"`.

All should work as expected.

Happy coding! 🖖

**Comment by titto-xavier** [comment]
@maximelafarie I also tried with it,but it shows following error

```
Uncaught Error: Template parse errors:
Can't bind to 'dismissable' since it isn't a known property of 'ngx-smart-modal'.
1. If 'ngx-smart-modal' is an Angular component and it has 'dismissable' input, then verify that it is part of this module.
2. If 'ngx-smart-modal' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<div id="rcyc-reqcall-modal" class="bodyContentOuter">


```

**Comment by khylias** [comment]
Hi @titto-xavier,

make sure that you correctly import NgxSmartModule in your app as below : 
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    NgxSmartModalModule.forRoot() // <----- don't forget about .forRoot() or .forChild()
  ],
  providers: [ ],
  bootstrap: [ AppComponent ]
})
```
