### ISSUE TITLE
Modal not totally closing

### ISSUE THREAD

**Issue by maximelafarie** [biig-io/ngx-smart-modal#119]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
As mentioned by @melicerte, when closing a modal with `closeLatestModal()`, the modal seems to be not totally closed and remains present in the DOM

**Expected behavior**
Modal should totally disappear from the DOM on method call.

* **Browser:** All

**Comment by maximelafarie** [comment]
After investigations, it seems this issue happens when the modal is called with `[dismissable]="false"`. Will try to fix this issue in incoming release.

**Comment by maximelafarie** [comment]
It seems that in some cases, the `body.dialog-open` class remains even if there's no modal opened.

**Comment by PinkiNice** [comment]
> It seems that in some cases, the `body.dialog-open` class remains even if there's no modal opened.

Got this bug when calling `router.navigate(['/'])` while modal is opened. 
Modal is getting closed but `body.dialog-open` remains, so scroll is hidden from the page.
Invoking `closeLatestModal()` does not help to return scroll.

**Comment by nickbanana** [comment]
> > It seems that in some cases, the `body.dialog-open` class remains even if there's no modal opened.
> 
> Got this bug when calling `router.navigate(['/'])` while modal is opened.
> Modal is getting closed but `body.dialog-open` remains, so scroll is hidden from the page.
> Invoking `closeLatestModal()` does not help to return scroll.

Still getting the issue at version 7.4.1, if the modal is opened/closed based on route navigation (i.e. /login open the modal)
