### ISSUE TITLE
Dismiss manually doesn't work

### ISSUE THREAD

**Issue by panagulis72** [biig-io/ngx-smart-modal#124]
Hi, I'm using ngx-smart-modal in an Angular 6/RxJs application to display a confirm dialog. The problem is that it seems you can create just one button, the 'close' button, that triggers myModal.close(). 
So, I thought I could add two buttons to allow the user to confirm or cancel the modal.
**CANCEL BUTTON**:
```
<button (click)="confirmModal.dismiss()" type="button">{{confirmModal.getData().cancelBtnLabel}}</button>
```
**CONFIRM BUTTON**:
```
<button (click)="confirmModal.close(true)" type="button">{{confirmModal.getData().confirmBtnLabel}}</button>
```

And then the component where there is the button to open the modal:
``` 
openConfirmModal() {    
    const confirmModalData: Object = {
       ...
      };
      this.ngxSmartModalService.setModalData(confirmModalData, 'confirmModal');
      let confirmModalRef = this.ngxSmartModalService.getModal('confirmModal');
      confirmModalRef.onDismiss.subscribe(() => {
        ....
      });
      confirmModalRef.onClose.subscribe((test: boolean) => {
        .....
      });
      confirmModalRef.open();
}
```

But if I click on cancel button, I have the following error in the console:
```
ERROR TypeError: Cannot read property 'target' of undefined
    at NgxSmartModalComponent.push../node_modules/ngx-smart-modal/esm5/ngx-smart-modal.js.NgxSmartModalComponent.dismiss
```

**Comment by maximelafarie** [comment]
Hi @panagulis72, thank you for reporting us this issue.

I reproduced your error on this [StackBlitz](https://stackblitz.com/edit/angular-m4tcyf).

**Comment by panagulis72** [comment]
Exactly, that one is the same error!

**Comment by maximelafarie** [comment]
So after checking your issue with the dev team, we've seen that there is no need to call the `dismiss` method externally. It a normal behavior (but the error message should be more explicit [I'll create a separated issue]).

`dismiss` is designed to "close" the modal when a click has been made on its backdrop. So if you want to close the modal, you shall use the `close` method.

But in your case, it seems you have "two ways" for closing your modal, so I recommend you to make two separated functions for each button, and do some actions. But both functions shall call the `close` method of the modal.

I hope it's clear and it helps you. Let me know if you need further informations. 🖖

**Comment by panagulis72** [comment]
First of all thank you for the support! 
Then, yes that should be a great approach. But I have nested modules, I have the 'items.module.ts' that is a Feature Module. Then, in the core (that is shared) module I defined the component for the confirm modal. So, I've written 
```
<router-outlet></router-outlet>
<ngx-smart-modal #myModal>
...my modal
</ngx-smart-modal>
```
in the items.component.html.
Then, I have a lazy-loaded edit-item.component.ts where I set the data of the modal (for example the title, the body etc, using the setData function).. so in the edit-item.component.ts I thought to subscribe onClose() function, and this works fine...but I need to know if the user want to "continue" or to "cancel" the operation.. and I can't write, for example:
```
<ngx-smart-modal #myModal>
...my modal
<btn (click)="customFunctionToDismiss()">
<btn (click)="customFunctionToContinue()">
</ngx-smart-modal>
```
because 'customFunctionToDismiss' and 'customFunctionToContinue' are going to be undefined. Neither, I can pass custom parameteters to the the close() function. 

I needed this behaviour because the target was to define the confirm-modal component just one time, and then use it in the whole application, even in the feature modules. If it is not clear, I could make a stackblitz. But I hope my case is going to be clear, and hope you have good a solution :D

**Comment by maximelafarie** [comment]
Hi @panagulis72, thank you for your well-explained case! 👌 

Yes please, I would really like you to make a StackBlitz in order to let me test some things on it! 😉

**Comment by panagulis72** [comment]
Hey @maximelafarie, I was wrong in my application. because I was doing a stackblitz for you, and it works :D I forked it, because maybe it could be useful to someone else [https://stackblitz.com/edit/angular-k9q4id?file=src/app/confirm-modal/confirm-modal.component.html](https://stackblitz.com/edit/angular-k9q4id?file=src/app/confirm-modal/confirm-modal.component.html)

**Comment by maximelafarie** [comment]
Well done @panagulis72! Thank you for the link, for sure it will help!
Cheers! 🖖 😉
