### ISSUE TITLE
How to switch back modal position to absolute position from app's level instead of parent's level ?

### ISSUE THREAD

**Issue by chanai-m** [biig-io/ngx-smart-modal#134]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I have upgrade ngx-smart-modal from v5.x to 7.x and found that position of my modals changes how it looks from v5.x which is using layout from app's position to using layout from parent's position.

My components structure design is stacked and able to call infinite. 
For example
    -Staff list component
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Show staff info
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Show department list component
    -Department list component
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Show department info
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Show staff list component
    -App root
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Show staff list component
so it will recursive call each other on click event.
Please take a look sample, In staff list choose 1 staff it will popup department list, Choose 1 department it will popup staff list and so on.
https://plnkr.co/l5snyhlMgsIkjODTTobt

After i changed to v7.x when using modal inside modal it will show inside main modal instead of app's position.
https://plnkr.co/WQw0fC6x5mcF7WB03lV2
Also i tried to use "target" but still not working.
https://plnkr.co/Ag5nLm

**Expected behavior**
Please take a look on my plnk for v5.x when using modal inside modal it will show in layout of app's position. 
https://plnkr.co/l5snyhlMgsIkjODTTobt

**Comment by khylias** [comment]
Hi @MonkeyDoll 

thank you for this detailed issue! 
I took a look at your code on examples, and I could notice that you declared `app-department` in the `app-staff modal`. As a result, the modal department is embedded in the staff modal. I advise you to position your modals at the same level, as on the `Modal Inception` example on [https://biig-io.github.io/ngx-smart-modal/](https://biig-io.github.io/ngx-smart-modal/).

If you have data to pass, you can use the methods `setModalData()`, `hasData()` and `getModalData()`.

Thanks for continuing to use our component, happy coding 🙌

**Comment by chanai-m** [comment]
Hi @khylias 
Thank you for your advice. I tried Modal Inception but it seem cannot use in my case. 
From what i know inorder to do infinity nested component is that put modal inside 2 components and those 2 components recursive call each other. I cannot put unknown number of modals into same level/root level since it can be infinity.

However, If my issue is not a bug or no plan to fix. I will reverse back to v5.x first and will try to override v7.x's css somehow.

**Comment by maximelafarie** [comment]
Hi @chanai-m! Thanks for this issue with good examples. I'll investigate your issue and I will come back to you with right code or fix if it's a bug (it would be a shame if you had to go back to a previous version of NgxSmartModal). 😉 

Cheers! 🖖

**Comment by maximelafarie** [comment]
@khylias to my mind, this issue is non-related to a bug of the library but a misunderstanding of its usage. Can we close this issue or do we have further checks to do before? 🤓

**Comment by maximelafarie** [comment]
Hi @chanai-m! Did you succeed to fix your issue? 😄 I'm sorry I tried each of your plunkr and the only solution I found is to change your implementations of the modal. 😕

**Comment by chanai-m** [comment]
Hi @maximelafarie,
I also have no solution yet. Only a solution is that using v5.x as long as you didn't change 5.x logic it should fine for me.

**Comment by maximelafarie** [comment]
Ok @chanai-m, nothing is planned to change the `5.x.x`. So can you tell me what makes your code working between the v5 and v7 please? It's really strange because the modal behavior isn't that different.

**Comment by chanai-m** [comment]
Hi @maximelafarie,
Sorry i do not understand your question. Could you please explain what do you mean for "what makes your code working between the v5 and v7" ?

From my code in plunker please click on "Launch in Editor" and as you can see code in 
v5 https://plnkr.co/l5snyhlMgsIkjODTTobt
and 
v7 https://plnkr.co/WQw0fC6x5mcF7WB03lV2
Both are almost exactly same code except v7 implemented CSS in index.html.

So to speak i didn't change anything just copy v5 and uninstall ngx-smart-modal and install ngx-smart-modal@7.x that's it. result will be very different in my case.

I am sure it is came from library but I honestly don't know which code, which part or even js or css from library affect the result. Anything i can help please let me know.

**Comment by maximelafarie** [comment]
Oh right, I didn't understand your problem at all. Actually I think your issue comes from a markup change between version 5 and 7. We refactored the modals template so you may need to adapt your style selectors if needed as explained in [this documentation part](https://github.com/biig-io/ngx-smart-modal#precautions-when-upgrading-to-a-newer-version).

Let me know if it helps you. Btw, I will potentially improve some lower versions in order to provide the same API for each version (from 5 I guess). But it's not prioritized on our roadmap for the moment. 

Cheers 🖖
