### ISSUE TITLE
Singleton instance of NgxSmartModalService for entire app

### ISSUE THREAD

**Issue by Kalpesh300** [biig-io/ngx-smart-modal#136]
**I'm submitting a ...**  
```
[ ] bug report 
[ ] feature request
[ x ] support request
```

In my Angular-6 application, there are many lazy-loaded modules. These modules have their own modals. As you mentioned in the documentation, I have to do  **NgxSmartModalModule.forChild()** in my child modules. I mentioned  **NgxSmartModalService** in **providers** array of my **AppModule**. But I want a singleton instance of **NgxSmartModalService** for my entire app. Is it possible to do that? If yes,  Can you please suggest me how to do that?

**Comment by maximelafarie** [comment]
Hi @Kalpesh300, 

[Angular documentation](https://angular.io/guide/singleton-services) provides informations about how you can use services as singleton. Try it out and come back to us, feedback are highly appreciated! 😉 

Cheers! 🖖

**Comment by maximelafarie** [comment]
@Kalpesh300 If you want a single service instance for all your app, you only have to declare the service as `.forRoot()` in a global module of your app. Let me know if you already resolved your issue. 

Happy coding! 🖖
