### ISSUE TITLE
getModalData method returns undefined

### ISSUE THREAD

**Issue by Kalpesh300** [biig-io/ngx-smart-modal#137]
**I'm submitting a ...**  
```
[ x ] bug report 
[ ] feature request
[ ] support request 
```

**Current behavior**
I am setting up some data with **setModalData** method. When I try to get data by using **getModalData** method I always get value undefined.

**Expected behavior**
It should return data which was set by **setModalData** method

**Comment by maximelafarie** [comment]
Hi @Kalpesh300, your issue is relative to #129 and will be fixed by 0e9bad4. 😉

**Comment by maximelafarie** [comment]
I assume we keep #129 for release tracking, so I'm closing this one. 🖖
