### ISSUE TITLE
Using in Angular 6

### ISSUE THREAD

**Issue by rsmachir** [biig-io/ngx-smart-modal#138]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
In angular6,  component just opens on to the page, instead of in a modal pop-up  No console errors.  Close and other features all work fine. 
**Expected behavior**

Expected to open

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Smart Modal version:** 0.8.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by khylias** [comment]
Hi @rsmachir ,

after some tests with Angular 6 and NgxSmartModal, I didn't find any bug as you describe. 
Check out on stackblitz below : https://stackblitz.com/edit/angular-tckfpe

I think you forgot to import the NgxSmartModal css file as indicated in the documentation: https://github.com/biig-io/ngx-smart-modal#setup 🤘 

If that's not your problem, I invite you to describe it more and reproduce the bug on a stackblitz for example. 😃 

Happy coding ! 👌

**Comment by rsmachir** [comment]
I did import NgxSmartModal, did not help.  No errors,  everything seems to work, except content just opens the div on the page itself instead of a popup.  Will try to reproduce the bug on stackbiz and get back to you.  Thank you.

**Comment by rsmachir** [comment]
I got it working now.  I had to add the NgxSmartModal CSS reference into my angular.json file instead of importing it into the main style sheet.  You an close this out now.  Thanks your help.

**Comment by mikeKane** [comment]
I apologize for reopening this issue, I am quite new to Ng and I am having the same issue. The Modal just opens at the div. 

I also do not have the css file imported, I am attempting to include it with the follow `"styles": [
              "src/styles.css",
               "src/ngx-smart-modal.css"
            ],` but the compiler complains this doesn't exit. I am using Ng 6.

**Comment by maximelafarie** [comment]
Hi @mikeKane, I answered you on #155. 😉
