### ISSUE TITLE
fail load images

### ISSUE THREAD

**Issue by BenbachirAzzedine** [biig-io/ngx-smart-modal#139]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
On the github.io the first example modal the image is not displayed.

**Comment by maximelafarie** [comment]
No need to fix it since lorempicsum.com seems to be up again! 👍
