### ISSUE TITLE
Cannot read property 'modal' of undefined

### ISSUE THREAD

**Issue by AmirGilboa** [biig-io/ngx-smart-modal#140]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

very basic angular 6 app, one modal component, i'm getting the error:
Cannot read property 'modal' of undefined
Stackblitz:
https://stackblitz.com/edit/angular-nlh8lw

muccho appreciated ;)

**Comment by khylias** [comment]
Hi @AmirGilboa,

I've took a look on your stackblitz and I found that you never import your modal component in your app.

You must import your component as below in your `app.component.html` :
```
<hello name="{{ name }}"></hello>
<app-modal></app-modal>
```
 And declare the component in `app.module.ts`: 
```
@NgModule({
  imports:      [ BrowserModule, FormsModule, NgxSmartModalModule.forRoot() ],
  declarations: [ AppComponent, HelloComponent, ModalComponent ],
  bootstrap:    [ AppComponent ]
})
```
Last point, if you use brackets notation, keep in mind that you must pass a string to the modal's identifier : 
```
<ngx-smart-modal #itemModal [identifier]=" 'itemModal' ">
```

Check all updates on : [https://stackblitz.com/edit/angular-drfdkq](https://stackblitz.com/edit/angular-drfdkq)

Happy coding 🤘

**Comment by AmirGilboa** [comment]
Ah, ok i get it now. Thanks so much for your help!
so we should include modal component in the calling page like this:
<modal-component></modal-component>
btw, i don't see this mentioned in the documentation, but maybe i just missed it.
anyways, it works now, thanks again.
