### ISSUE TITLE
Close on 'Escape'

### ISSUE THREAD

**Issue by malchijah** [biig-io/ngx-smart-modal#15]
Unable to close the modal on 'escape'.

**Comment by maximelafarie** [comment]
@malchijah Thank you for this report. I will fix it tomorrow and let you know about the progression of this issue!

**Comment by malchijah** [comment]
Thank you Max! That was quick!

**Comment by maximelafarie** [comment]
@malchijah It is done! Now you can update `ngx-smart-modal` to the **2.0.3** version. 😉 
Now, all modals are, by default, listening for an **escapek key press event**. 
It will close the current opened modal, or the latest opened if you have several modals opened at the same time.
You can disable this behavior by setting the `[escapeAble]` option to `false` on the desired `<ngx-smart-modal>...</ngx-smart-modal>` element.

Hope it will fit your needs.

Have a nice day.

P.S.: I will write something about this new behavior in the docs. :)

**Comment by malchijah** [comment]
Awesome.. Thank you Max. I'll check it out. :)
