### ISSUE TITLE
CSS Causes Error

### ISSUE THREAD

**Issue by mikeKane** [biig-io/ngx-smart-modal#155]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```
**Current behavior**

importing the css causes errors 
`ERROR in ./src/styles.css (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./src/styles.css)
Module build failed (from ./node_modules/postcss-loader/lib/index.js):
Error: Can't resolve 'ngx-smart-modal/ngx-smart-modal' in '/Users/_kane7161/app/src'
   `
**Expected behavior**

I would expect to import the css file and the project would build
**Reproduction of the problem**
Import using this statement in styles.css 
`/* You can add global styles to this file, and also import other style files */
@import "~ngx-smart-modal/ngx-smart-modal";`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

macOS 13.4
* **Smart Modal version:** 0.8.x

* **Angular version:** 2.0.x

```Angular CLI: 6.2.6
Node: 9.11.1
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.6
@angular-devkit/build-angular     0.8.6
@angular-devkit/build-optimizer   0.8.6
@angular-devkit/build-webpack     0.8.6
@angular-devkit/core              0.8.6
@angular-devkit/schematics        0.8.6
@angular/cli                      6.2.6
@angular/fire                     5.1.0
@ngtools/webpack                  6.2.6
@schematics/angular               0.8.6
@schematics/update                0.8.6
rxjs                              6.2.2
typescript                        2.9.2```
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
<!-- All browsers where this could be reproduced -->
Chrome
Safari
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by maximelafarie** [comment]
Hi @mikeKane! 
Firstly, thank you for using our library and for posting a full detailed issue! 😉 

If you want to import `scss` styles of the library, you can import it this way (without specifying the file extension): 
```scss
@import "~ngx-smart-modal/ngx-smart-modal";
```

So in your case, if you're not using any style preprocessor and want to use `css` only, you have to import the library style file this way (please note the `.css` at the end of the import path):
```css
@import "~ngx-smart-modal/ngx-smart-modal.css";
```

Let me know if it solves your issue!

Happy coding! 🖖

**Comment by mikeKane** [comment]
Thank you sooo much! This worked. Your library is fantastic. 

If I may ask 1 more small question, is this the correct way to attach a class? This doesn't seem to go from bottom to top. `<ngx-smart-modal class="nsm-dialog-animation-btt" #myModal identifier="myModal">
    <h1>Title</h1>
    <p>Some stuff...</p>
    <button (click)="myModal.close()">Close</button>
  </ngx-smart-modal>`

Also can I make the modal as big as I want?

**Comment by mikeKane** [comment]
Trying this from a nav bar does not work. 

`
<nav class="navbar navbar-light navbar-3 state">

    
    
    <span class="navbar-text">
           <a [routerLink]="['/']" routerLinkActive="router-link-active" >FoodTruckIT</a>
          </span>

    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent15" aria-controls="navbarSupportedContent15"
        aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

    
    <div class="collapse navbar-collapse" id="navbarSupportedContent15">

        
        <ul class="navbar-nav mr-auto">
            
            <li class="nav-item food-style">
                <a class="nav-link" href="https://itunes.apple.com/us/app/foodtruckit/id1332334724?mt=8">Download on the Apple App Store</a>
            </li>
            <li class="nav-item food-style"><div id="modal-container" class="hidden"></div>
<div id="overlay" (click)="removeModal()" class="hidden"></div>
                <a class="nav-link" href="mailto:foodtruckitapp@gmail.com">Contact</a>
            </li>
            <li class="nav-item food-style">
                <a class="nav-link" [routerLink]="['/privacy']" routerLinkActive="router-link-active" >Privacy Policy</a>
            </li>
        </ul>
        
        <button (click)="ngxSmartModalService.getModal('myModal').open()">Open myModal</button>
    </div>
    
</nav>
`

`<ngx-smart-modal customClass="nsm-dialog-animation-btt"  #myModal identifier="myModal">
    <h1>Title</h1>
    <p>Some stuff...</p>
    <button (click)="myModal.close()">Close</button>
  </ngx-smart-modal>`

App-Component.html
`<app-navbar></app-navbar>
<div class="hr"></div>
<app-marker-view></app-marker-view>
<router-outlet></router-outlet>
<div class="hr"></div>
<app-footer></app-footer>`

Is this expected?

**Comment by khylias** [comment]
Hi @mikeKane,

If you wish that we debug your app, please provide us a stackblitz.

However your question is about a personal project or modal implementation, please ask this on stackOverflow.

**Comment by maximelafarie** [comment]
Awesome! Thank you for the kind words @mikeKane! 😄 
Sure! Feel free to contribute if you want! 😉 

So is your first issue resolved? If it is, please open a new issue with your new problem in order to avoid off-topic issues or issues with mixed problems.

Cheers! 🖖

**Comment by LewBlu** [comment]
For anyone that attempts to use this with Angular 18+, the import of the styles has changed slightly due to the use of Vite.
It is now simply `@import "ngx-smart-modal/styles";` since Vite does not need the leading `~` and uses the export to find the css/scss file to use.
