### ISSUE TITLE
Unable to override a component with a lower z-index and an absolute position

### ISSUE THREAD

**Issue by eb245** [biig-io/ngx-smart-modal#156]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
We have a navbar in an application with an absolute position and a z-index of 1. When we open an ngx-smart-modal, the dialog is hidden behind it. We have tried setting the z-index and position of the dialog, but it doesn't override the navbar.

**Expected behavior**
The modal should display with the overlay in front of the navbar

**Reproduction of the problem**
There is a rudimentary example here: 
https://stackblitz.com/edit/angular-x2vrvb?file=src%2Fapp%2Fapp.component.html

**What is the motivation / use case for changing the behavior?**
It's the normal behavior of the bootstrap modal, which we are changing from.

**Please tell us about your environment:**
windows 10 and fedora 22, angular 2, npm

* **Smart Modal version:** 0.8.x
7.1.0

* **Angular version:** 2.0.x
Angular 2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 56 & firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 3

**Comment by khylias** [comment]
Hi @eb245 ,

Thanks for format your issue and stackblitz 🤘 
It seems that you didn't import the ngx-smart-modal.sccs in your project as below : 
[https://github.com/biig-io/ngx-smart-modal#style--customization](Styles & Customization)

Happy coding 🙌
