### ISSUE TITLE
Unable to use custom directive *new*

### ISSUE THREAD

**Issue by astr0sl0th** [biig-io/ngx-smart-modal#163]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When using custom directives within a ngx-smart-modal it has no effect on the element it is being applied to

**Expected behavior**
Directive should function as normal

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Smart Modal version:** 0.8.x
@next

* **Angular version:** 2.0.x
7
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by maximelafarie** [comment]
Hi @astr0sl0th, we never experienced a such issue, could you make a reproduction of this bug on Stackblitz please?

**Comment by astr0sl0th** [comment]
https://stackblitz.com/edit/ngx-smart-modal-example-v7gzyx

**Comment by astr0sl0th** [comment]
Ahhh turns out it is a z-index issue with the modal. Google places autocomplete is being hidden behind the modal. That is why my directive appears to not be working :(

**Comment by maximelafarie** [comment]
I don't understand what's wrong, your directive is working well:
![2018-11-20 16 08 26](https://user-images.githubusercontent.com/5319267/48782512-a5999200-ecde-11e8-9498-103e3c5d39c6.gif)

**Comment by maximelafarie** [comment]
Oh right! I just saw your last message, is all ok for you now? 😁

**Comment by astr0sl0th** [comment]
Well technically it 'works' but is being hidden but the z-index computation by ngx-smart-modal. Can I override the z-index of a certain modal?

**Comment by astr0sl0th** [comment]
Sorry I think i shared the wrong stackblitz as it was mean to be showing a google places auto complete directive on a input/text field

**Comment by maximelafarie** [comment]
Yes, you can override any modal style property by providing a class that overrides it in the `customClass` option.
No problem! 😉

**Comment by astr0sl0th** [comment]
@maximelafarie Thanks for your explanation and work on ngx-smart-modal. Much appreciated.

**Comment by maximelafarie** [comment]
@astr0sl0th Thank you for the kind words! 
Cheers! 🖖
