### ISSUE TITLE
Return result data when modal close

### ISSUE THREAD

**Issue by Thomas0921** [biig-io/ngx-smart-modal#172]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I think I can pass data to modal, but could not find a way to get the data back when dismiss.

**Expected behavior**
Like the modal in ionic framework, you can pass data to modal, and get the data back when dismissed.

**Reproduction of the problem**
1. put ngx-smart-modal directive in a child component
2. after doing some calculation on the modal, need to take the result back to parent component.
3. But no approach for me to get the result data when the modal close.

**Comment by maximelafarie** [comment]
Hi @Thomas0921!
This modal is clearly related to #168 and will be implemented in next versions. I guess what you're asking for is chaining the modal methods. E.g. `this.modalService.close().getData()`; This way you can chain actions. 

But at the moment, it's possible to get data on dismiss as you want. You can refer to the [Handle events](https://github.com/biig-io/ngx-smart-modal#handle-events) readme section, and subscribe / listen to `onDismiss` event. Here's a quick example in your case, with documentation example:

```
export class AppComponent implements AfterViewInit {
  ...
  constructor(public ngxSmartModalService: NgxSmartModalService) {
  }

  ngAfterViewInit() {
    this.ngxSmartModalService.getModal('videoModal').onDismiss.subscribe((modal: NgxSmartModalComponent) => {
      // modal is the dismissed modal, so do what you want with it
      console.log('Modal data', modal.getData());
    });
  }
}
```

Let me know if it works for you!

Cheers! 🖖

**Comment by Thomas0921** [comment]
Hi, thanks for the detailed reply, I manage to achieve the effect I want by using angular core's event emitter. So that I will not need to listen for changes, just fire once when modal close :). I haven't tested it out, but I will use your approach if I still face any error here :) Thanks again
