### ISSUE TITLE
destroy the modal on close

### ISSUE THREAD

**Issue by avifatal** [biig-io/ngx-smart-modal#173]
Hi,
Is it possible to totally destroy the modal whenever it is closed.
it seems that when a modal with text input, and it is reopened, it is opened with old state. (the input has text inside).
I want to have a totally new compoenent each time. possible.
Thanks

 Video demonstration...
https://streamable.com/s/t5zww/ppgchz

**Comment by khylias** [comment]
Hello @avifatal,

thank you for your interest in Ngx-smart-modal. 
First, modify your problem with the default problem template that you probably skipped.

Did you know that you can share your Stackblitz URL?

In your case, the modal is just close and by default, Ngx-smart-modal doesn't destroy itself on any close events. You can reset your modal data by subscribe `onAnyCloseEvent` and use `resetModalData` or reset your local const.

Happy Coding 🤘

**Comment by avifatal** [comment]
Thanks

**Comment by maximelafarie** [comment]
Hi @avifatal, I would also add that you can call the [`removeModal`](https://github.com/biig-io/ngx-smart-modal/blob/master/src/ngx-smart-modal/src/services/ngx-smart-modal.service.ts#L159) method of the `NgxSmartModalService` to destroy a modal instance at any time. So after close, you can call this method to completely destroy the modal. 

Cheers! 🖖

**Comment by Meigyoku-Thmn** [comment]
I see that even with `removeModal`, the corresponding ngx-smart-modal element is not removed from html. Is it the normal behavior or a bug?
Everytime I open my modal, I do like this:
```js
this.modalService.removeModal(MY_MODAL);
    this.modalService.create(MY_MODAL, MyModalComponent)
      .setData(data)
      .open();
```

**Comment by sanderschnydrig** [comment]
removeModal will prevent the modal from being opened again though

**Comment by Iuriy-Budnikov** [comment]
Thae problem of that compenant that it's doesn't destroy components inside!
