### ISSUE TITLE
Is there any way I can make modal draggable?

### ISSUE THREAD

**Issue by songzhm** [biig-io/ngx-smart-modal#176]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Modal is in fixed position

**Expected behavior**

Modal can be dragged around

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Make the modal position more dynamic, so user can have interactions with other elements while the modal is appearing. 

**Please tell us about your environment:**

Operating system: macOS Mojave
IDE: WebStorm
package manager: NPM

* **Smart Modal version:** 7.1.1

* **Angular version:** 7.2.0

* **Browser:** [Chrome XX ]

* **Language:** [all | TypeScript 3.2.2 | ES6/7 | ES5]

**Comment by maximelafarie** [comment]
Hi @songzhm and thank you for submitting us this issue!

The feature you're asking for is quite cool, but not implemented yet. You should implementing it yourself for the moment (we will maybe implement it in the future but there's no release planned to implement that for the moment).

You can use third-party libraries, and target the modals to make them draggable or develop your own solution to drag them across the screen.

I'm at your disposal if you need any help achieving this. I [made a Stackblitz](https://ngx-smart-modal-draggable.stackblitz.io/) as a starting point to play with draggable modals. 😉 

I keep this issue opened as a reference and ticket to add to our roadmap for v8 potential features.

Cheers! 🖖

**Comment by maximelafarie** [comment]
I updated the link to StackBlitz in order to share the code with you. The dragging function comes from the W3School and has been adapted for this case. 🤘

**Comment by maximelafarie** [comment]
Since there's no more asking for a such feature and no response on this issue as well, we chose to remove this feature from the backlog, in agreement with @marco10024.
Cheers! 🖖

--

> Reference and source code to help you realizing this feature on your projects: https://stackblitz.com/edit/ngx-smart-modal-draggable
