### ISSUE TITLE
Need to be able to simply specify a component to be opened in a modal

### ISSUE THREAD

**Issue by thardy** [biig-io/ngx-smart-modal#184]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

I have to place the template for the modal inside the template of a component already displayed.  Reusable modals can't simply live on their own.  I have to find a weird place for their templates to live.

**Expected behavior**

I would like to be able to tell NgxSmartModalService to open a component with it's own template and code, so that I don't have to place the modal template in some other component's template.

e.g. this.ngxSmartModalService.open(new SomeComponentIWantInAModal(), someData);

Most other Angular modal frameworks support some form of this.

**Reproduction of the problem**

This has to live in a particular place (where it doesn't necessarily belong), making it impractical for reuse.
```
<ngx-smart-modal #myModal identifier="myModal" [customClass]="myModalClass">
... cool modal code here ...
</ngx-smart-modal>
```
**What is the motivation / use case for changing the behavior?**

The current implementation promotes tight coupling between the consumer of the modal and the modal template itself. 

It is preferable to have modular modals that can be reused all over my app, plus the ability to dynamically select a modal in code without all possible templates having to be present in the template that wants to pop the modal.

**Please tell us about your environment:**

Windows 10, WebStorm, npm, IIS

* **Smart Modal version:** 0.8.x

7.1.1

* **Angular version:** 2.0.x

7.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.1.6

**Comment by maximelafarie** [comment]
Hi @thardy!

There's an existing issue about that: #171, you may find some answers in it. It's kind of a big deal since the library hasn't been designed to work like that (even if other libs implemented it). If you want to make a PR with some code to make this available on the lib, it would be a pleasure to review it! 😉 

Regards! 🖖

**Comment by maximelafarie** [comment]
Closing this one in favor of #171! 🖖
