### ISSUE TITLE
Select DropDown is showing out of modal

### ISSUE THREAD

**Issue by lokeshreddy1706** [biig-io/ngx-smart-modal#196]
**I'm submitting an issue**  (check one with "x")

**Current behavior**
When I use the select dropdown in Modal and when I open it, Drop Down is showing out on the blurred backdrop.

**Expected behavior**
Modal needs to adjust the height/width dynamically based on the content in it.

**Reproduction of the problem**
Create a select drop down in Modal and try to open it. Please refer screenshot and below is the stackblitz link

![ngx-smartModal-selectbox-issue](https://user-images.githubusercontent.com/8534808/54089278-69716680-438d-11e9-8a38-8b3c96a4fe09.jpg)

https://ngx-smartmodal-selectbox-issue.stackblitz.io

**What is the motivation / use case for changing the behavior?**
For better Product

**Please tell us about your environment:**

Windows 10
* **Smart Modal version:** 7.1.1.

* **Angular version:** 7.2.8

* **Browser:** [all ]

* **Language:** [TypeScript X.X ]

**Comment by maximelafarie** [comment]
Hi @lokeshreddy1706,

It seems to be the standard behavior for modals. Have you tried to add `overflow: visible;` CSS rule to the modal container in order to make the modal's content to fit the dropdown?

Let me know if it solved your issue.

Cheers! 🖖
