### ISSUE TITLE
Add a11y to modal

### ISSUE THREAD

**Issue by maximelafarie** [biig-io/ngx-smart-modal#203]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Actually, there's no accessibility (or minor) to modals and their actions. 

**Expected behavior**

Add right a11y to modals according to best practices. (`aria-` attributes)

**Reproduction of the problem**

Nothing special to reproduce.

**What is the motivation / use case for changing the behavior?**

Don't break the a11y of any project which uses this library and provide good a11y in any cases.

**Please tell us about your environment:**

Nothing special.

* **Smart Modal version:** 0.8.x

Any.
Should be released in a `minor` version.

* **Angular version:** 2.0.x

Any.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All.

**Comment by maximelafarie** [comment]
Inspection of team @biig-io/integration is advised.

**Comment by maximelafarie** [comment]
@LouisAugry you can fix your PR conflicts now @marco10024's PR has been merged! 🎉 
Cheers! 🖖

**Comment by marco10024** [comment]
Feature added, PR #238
