### ISSUE TITLE
Can't open next modal at once after closing previous one.

### ISSUE THREAD

**Issue by Voskan** [biig-io/ngx-smart-modal#204]
when I click immediately after closing previous one  modal is not opening .

video: https://yadi.sk/i/SCQLb6W0qZHa6A

https://embed.plnkr.co/Ag5nLm/

**Comment by maximelafarie** [comment]
Hi @Voskan and thank you for these examples.

You can play with the `hideDelay` option, and use it like: `[hideDelay]="200"`. It should solve your issue. 😉 

Here's the working example : https://next.plnkr.co/edit/yFNgj0gAKBCwZRV5?preview

Let me know if it solves your issue.

Cheers! 🖖

**Comment by Voskan** [comment]
thanks a lot, it solved my problem
