### ISSUE TITLE
$dialog-position-top set all margin values of modal window

### ISSUE THREAD

**Issue by cube27rus** [biig-io/ngx-smart-modal#207]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
overriding $dialog-position-top set all margin values of modal window, and my window becomes too small

**Expected behavior**
I expect that $dialog-position-top should set top value

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Chrome

* **Smart Modal version:** 0.8.x
7.1.1

* **Angular version:** 2.0.x
7

**Comment by khylias** [comment]
Hi @cube27rus ,

thanks for your formatted issue. I provide a stackblitz to illustrate this behavior : [https://stackblitz.com/edit/ngxsmartmodal-expressionchangedafterithasbeencheckederro-eqcvsb](https://stackblitz.com/edit/ngxsmartmodal-expressionchangedafterithasbeencheckederro-eqcvsb)

As you can see, the `$dialog-position-top` set all margins properties. I'll post a PR asap. 🤘
