### ISSUE TITLE
Dismissing modal not working properly

### ISSUE THREAD

**Issue by wiktor-mazur** [biig-io/ngx-smart-modal#212]
**I'm submitting a ...**
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When you click somewhere inside the modal, then you move your mouse onto the backdrop (while still pressing the mouse button), and then you release it, the modal gets dismissed. This is pretty annoying when you have inputs in the modal and you try to select their contents with the mouse (usually you go outside the modal before releasing the button and thus, the modal closes).

**Expected behavior**
Modal should only close when you click directly on the backdrop.

* **Smart Modal version:** 7.1.1

* **Angular version:** 7.2.6

* **Browser:** all

* **Language:** all

**Comment by maximelafarie** [comment]
Hi @wiktor-mazur and thank you for your issue.
Indeed, it seems it's a bug related to the kind of event the backdrop is listening to. We need to make a more accurate check before dismissing the modal. 

I add it to the May Release Milestone. 

Cheers! 🖖

**Comment by patrickcorrigan** [comment]
Can also confirm this issue. Problem when highlighting text inside a modal and you release outside of modal.

**Comment by maximelafarie** [comment]
Thank you @patrickcorrigan for confirming this issue. I can also confirm I was able to reproduce this issue. This is one of our priorities for the very soon May release! 😉

**Comment by wiktor-mazur** [comment]
Hello. When are you planning to release new npm version?
