### ISSUE TITLE
Multiple CSS Classes on [customClass] Problem!

### ISSUE THREAD

**Issue by keyrox** [biig-io/ngx-smart-modal#219]
**I'm submitting a ...** (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When informing multiple CSS classes through the [customClass] attribute the component is removing all the white spaces between the class names.
So in this scenario: `[customClass]="form-dialog dialog-large"` then end result on the html ends up being 
```html
<div class="nsm-dialog form-dialogdialog-large nsm-dialog-open" ng-reflect-ng-class="nsm-dialog,form-dialog dial" [...]>
```

**Expected behavior**
When iforming multiple CSS classes on the [customClass] the classes should be included in the container preserving the white spaces:
```html
`<div class="nsm-dialog form-dialog dialog-large nsm-dialog-open" [...]>`
```

**What is the motivation / use case for changing the behavior?**
In my case, I have a custom component to encapsulate the application dialogs and all the attributes are customized, generating multiple CSS classes that need to be applied to the container.

* **Smart Modal version:** 7.1.1

* **Angular version:** 8.1.2

* **Browser:** Chrome

* **Language:** TypeScript 3.4.5

**Comment by keyrox** [comment]
First of all, I would like to congratulate you for the great work you have put int this package. It's a great component and I am pretty sure is aggregating value in many projects. Let me know if you have any problem reproducing this issue.

And thank you in advance.

**Comment by keyrox** [comment]
Nevermind, just found out that for some reason my component had `preserveWhitespaces: false` on it.

**Comment by maximelafarie** [comment]
Hi @keyrox! I'm glad you solved your issue! 😄 

Thank you very much for the kind words, we really appreciate! 💯 
Feel free to drop an issue in case you're facing some bugs or if you have questions about the package. 
Again, thank you for the compliments and for using our library! Happy coding!

Regards 🖖
