### ISSUE TITLE
Content of ngx-smart-modal, like some component inside, initialize at once

### ISSUE THREAD

**Issue by helen31** [biig-io/ngx-smart-modal#220]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

<ngx-smart-modal #myModal identifier="myModal">
  <header>
    <p>It is a header</p>
  </header>
    <app-some-component></app-chat-some-component>
  <button (click)="myModal.close()">Close</button>
</ngx-smart-modal>

SomeComponent  class (content of the ngx-smart-modal) is created and initialized at once, but not when modal is opened.

**Expected behavior**

I expected that SomeComponent initialize and destroy when modal initialize and destroy.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Smart Modal version:** 0.8.x

7.1.1

* **Angular version:** 2.0.x

8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by khylias** [comment]
Hi @helen31, 
I understand your request, however the operation of the library controls the modal and not its content, to give the developers flexibility.
For your problem, you can put an `ngIf` on your SomeComponent that validates when the modal opens and invalidates when it closes. Let's do that with `onOpen` and `onAnyCloseEventFinished` events emitter. This way it will initialize itself with each opening.

Happy coding 🤘
