### ISSUE TITLE
proper width is not coming for smart dialog

### ISSUE THREAD

**Issue by vermpr** [biig-io/ngx-smart-modal#221]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```
Hi 
I was using ngx-smart-modal,I am adding an iframe inside the modal.
I wanted the width and height of ngx-smart-modal to 90% cover my page and iframe contents to be fully displayed..
I used customClass as large-modal. however, The width and height of ngx modal is coming less then what i expected and its hiding my iframe content.
i tried to use custom style as follows:
sample-modal
{
max-width:none !important
}
and set as customClass=["'sample-modal'"]
its not making this css class effective.
I am using modal as follows.
<ngx-smart-modal [custom-class]="'large-modal'" identifier="sampleModal">
<div class="model-body">
<iframe src="xyz.com" scrolling="no" width="90%" height="90%>
</iframe>
</div>
</ngx-smart-modal>
Looking forward for any leads on this.
Thanks!

**Current behavior**

 dialog modal is not having width and height  to cover iframe contents.
**Expected behavior**

dialog modal should fill/cover iframe contents like rickroll events.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Smart Modal version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by khylias** [comment]
Hi @vermpr ,

With your little code extract, I can see that you didn't declare the `customClass` correctly.
```
<ngx-smart-modal #videoModal identifier="videoModal" [customClass]="'medium-modal'">
```
