### ISSUE TITLE
Select2 plugin in ngx-smart-modal doesn't work

### ISSUE THREAD

**Issue by amin79** [biig-io/ngx-smart-modal#230]
Hello,

here the link of the problem in stackoverflow:

https://stackoverflow.com/questions/58098336/select2-plugin-in-ngx-smart-modal-doesnt-work

**Comment by maximelafarie** [comment]
Hi @amin79.

Please use the issue template when creating a new issue and please add reproduction link on StackBlitz for example. This also applies for StackOverflow post.

Cheers 🖖
