### ISSUE TITLE
create method not available on npm package

### ISSUE THREAD

**Issue by vitokodev** [biig-io/ngx-smart-modal#231]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Unable to use `create` method.

**Expected behavior**
Being able to use the `create` method.

**Reproduction of the problem**
I have the lastest version of this module (already ran `npm i ngx-smart-modal @latest` to make sure about that).

There is a difference on `src/ngx-smart-modal/src/services/ngx-smart-modal.service.ts` between Github and the NPM package regarding this function (and most likely other functions).

**What is the motivation / use case for changing the behavior?**
I need to instantiate modals depending on specific cases catching the instance.

**Please tell us about your environment:**

Windows 10. NPM 6.9.0. NodeJS 10.16.0

* **Smart Modal version:** 0.8.x
7.1.1

* **Angular version:** 2.0.x
7.3.9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by maximelafarie** [comment]
Hi @vitokodev,

Indeed, since we hadn't released the new `v7.2.0` yet, so you couldn't use the newest methods. 

I'm happy to tell you that version `7.2.0` has just been released now, and that you can from now use the latests methods.

Please excuse us for the inconvenience and let us know if you encounter any issues.

Best regards! 🖖
