### ISSUE TITLE
Change Color of Dialogue-Btn-Close?

### ISSUE THREAD

**Issue by dkuhrmeyer** [biig-io/ngx-smart-modal#251]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I would like to change the color of the close button ("X").

When I inspect the element of nsm-dialogue-btn-close, it looks like there is an image tag.
<img src="data:image/svg+xml...../>
I was trying to manipulate the fill via CSS and could not change the color.

Is there a way to do this or could this be a new feature.  Thank you in advance

**Expected behavior**

There should be an easy way to change the color of the Btn-Close
**Reproduction of the problem**

Not necessary
**What is the motivation / use case for changing the behavior?**

Better User Experience
**Please tell us about your environment:**

Angular 7 project
* **Smart Modal version:** 0.8.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by khylias** [comment]
Recently, we merged a [contribution](https://github.com/biig-io/ngx-smart-modal/pull/246) to change the image tag to an SVG, however we have not yet published this version on NPM.

**Comment by dkuhrmeyer** [comment]
Thank you for the speedy response.  Will you be publishing this change via NPM in the near future?

**Comment by khylias** [comment]
We merge some important features, we'll release them very soon !

**Comment by khylias** [comment]
@dkuhrmeyer 7.3.0 is just released! You can update your package and change the color with the new SVG icon. :metal:

**Comment by dkuhrmeyer** [comment]
thank you very much!

**Comment by dkuhrmeyer** [comment]
I updated my package and am trying to change the color of the SVG icon.  Attached are the different strategies I've used to change the color:

::ng-deep .nsm-dialog-btn-close .currentColor {
  fill: rgb(255, 158, 44);
}

or

::ng-deep .nsm-dialog-btn-close svg {
  fill: rgb(255, 158, 44);
}

or

::ng-deep .nsm-dialog-btn-close {
  fill: rgb(255, 158, 44);
}

I've tried adding these 3 different strategies to my component scss file and my root scss file.  Can you give me direction on how to change the color of the .nsm-dialog-btn-close icon?  Thank you in advance

**Comment by FrciSmrci** [comment]
> I updated my package and am trying to change the color of the SVG icon. Attached are the different strategies I've used to change the color:
> 
> ::ng-deep .nsm-dialog-btn-close .currentColor {
> fill: rgb(255, 158, 44);
> }
> 
> or
> 
> ::ng-deep .nsm-dialog-btn-close svg {
> fill: rgb(255, 158, 44);
> }
> 
> or
> 
> ::ng-deep .nsm-dialog-btn-close {
> fill: rgb(255, 158, 44);
> }
> 
> I've tried adding these 3 different strategies to my component scss file and my root scss file. Can you give me direction on how to change the color of the .nsm-dialog-btn-close icon? Thank you in advance

For anybody looking for the solution in the future, you can use the [filter](https://developer.cdn.mozilla.net/en-US/docs/Web/CSS/filter) css property. Here's an awesome [codepen](https://codepen.io/sosuke/pen/Pjoqqp) converting the hex to a filter value.
