### ISSUE TITLE
Bindings and Life cycle hooks do not work on dynamic component

### ISSUE THREAD

**Issue by barryajones** [biig-io/ngx-smart-modal#255]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

From my app.component I am creating a new modal instance with a component **ModalViewComponent**. (_The component has been added to the entryComponents._)

```
this.ngxSmartModalService.create('testModal', ModalViewComponent).open();
```

The modal opens correctly but the lifecycle hooks (`ngOnInit`, `ngAfterViewInit`) of the dynamically loaded component are not called. I have also observed that the template bindings are not working. In the dynamically loaded component there is binding for `title` that does not render.

**Expected behavior**

Lifecycle hooks are called and template bindings work.

**Reproduction of the problem**

I have created a stackblitz that shows the issue. Clicking the Open Modal button displays the modal but none of the lifecycle hooks are called and the template bindings do not render.

https://stackblitz.com/edit/ngx-smart-modal-lifecycle

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Smart Modal version:** 7.3.0

* **Angular version:** 8.2.9

* **Browser:** Chrome 78.0.3904.97

* **Language:** all

**Comment by khylias** [comment]
Hi @barryajones ,

thanks to reporting this issue (with a stackblitz :metal:) ! I'll check this asap.

**Comment by maximelafarie** [comment]
Hi @barryajones!
I think this issue is complementary with this one #235. It seems this is common for a lot of projects that would like to handle content projection with dynamic content. 🤔

**Comment by maximelafarie** [comment]
Closing it in favor of #235, please follow the evolution of this fix in this issue. 😉
Cheers! 🖖
