### ISSUE TITLE
How to make modal full screen

### ISSUE THREAD

**Issue by Teebo** [biig-io/ngx-smart-modal#256]
Hi, I would like to make the modal full screen, I would like to have a div with a background-image in it.
Is there maybe a property to set it as full screen?

I tried with using a custom class like `[customClass]="'full'"` but that did not work

**Comment by maximelafarie** [comment]
Hi @Teebo,
You need to add your own custom class in a global style file of your project (e.g: `styles.scss` or any stylesheet imported into it), `. full` for example, then apply it as you've done : `customClass="full"`. 
You can get some more info [on the docs](https://biig-io.github.io/ngx-smart-modal/#/style).

Let me know if it's good for you! 😉 

Regards! 🖖

**Comment by Teebo** [comment]
Hi @maximelafarie that worked perfcectly! thank you, and thank you for creating such an awesome package. 😀

**Comment by maximelafarie** [comment]
Thank you very much for the kind words @Teebo! 😀 
Happy coding! 🖖
