### ISSUE TITLE
Ability to change the cross

### ISSUE THREAD

**Issue by Nek-** [biig-io/ngx-smart-modal#261]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Hardcoded cross inside modal

**Expected behavior**
Possibility to remove or personalize the cross.

**Reproduction of the problem**
Any modal have it.

**What is the motivation / use case for changing the behavior?**
Well, I have a designer that made another cross. Changing it is a pain ATM.

**Please tell us about your environment:**
whatever it's not environment-related

* **Smart Modal version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** all

* **Language:** TypeScript X.X

**Comment by LouisAugry** [comment]
What do you want to change the cross? The possibility of passing a SVG ?

With @maximelafarie , we had thought of removing the SVG cross and replacing it with a unicode symbol by default.

**Comment by Nek-** [comment]
I think the ability to remove it completely would be nice (adding a button with a custom SVG or something else is not a big deal, no need to have special customization available from the plugin options)

**Comment by khylias** [comment]
@Nek-  If you didn't want to deal with the icon, actually you can set the `closable` parameters to `false`.

**Comment by maximelafarie** [comment]
@Nek- I understand what you want, and that was one of the first idea I got about this icon. But as @khylias said, you can finally set the `closable` option to `false` and add your own icon / button with `(click)="yourModalRef.close()"`. 😉 Let me know if it can fit your needs or if you really think a such feature will be useful! 🖖

**Comment by Nek-** [comment]
God. I missed it in the documentation. Everything looks perfect here.
