### ISSUE TITLE
Pass data to ViewRef resulting from TemplateRef content

### ISSUE THREAD

**Issue by GerkinDev** [biig-io/ngx-smart-modal#268]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Currently, there's no way to set the context of the view when passing a TemplateRef to `NgxSmartModalService.create`.

**Expected behavior**
The context of the ViewRef should be sync with the data of the modal.

**Reproduction of the problem**
Example use case here: https://stackblitz.com/edit/ngx-smart-modal-example-4vbtak

**What is the motivation / use case for changing the behavior?**
I need this because I cannot scope the `ngx-smart-modal` component inside the part of the component that have access to my data, and that is refreshed regularly. So, I need to be able to inject data from anywhere, in a template, and use `let-foo` to get the `foo` context property.

**Please tell us about your environment:**
In a poor condition :evergreen_tree: :fire: 

* **Smart Modal version:** 7.3.0

* **Angular version:** 8.2.13

* **Browser:** all

* **Language:** TypeScript

---

**Possible implementation**
Setting the [context](https://angular.io/api/core/EmbeddedViewRef#context) of the [EmbeddedViewRef](https://angular.io/api/core/EmbeddedViewRef#context) created in [NgxSmartModalService](https://github.com/biig-io/ngx-smart-modal/blob/master/src/ngx-smart-modal/src/services/ngx-smart-modal.service.ts#L431) works (I just tried). So the EmbeddedViewRef reference should be stored somewhere to be reused when calling `NgxSmartModalService.setData`.

I can PR :beers:

**Comment by LouisAugry** [comment]
Can you try again locally with the latest version of master please. @maximelafarie fixed this problem I think

**Comment by GerkinDev** [comment]
I have just checked, and it seems that this issue is not closed by merged PR #266

**Comment by LouisAugry** [comment]
Look at [https://biig-io.github.io/ngx-smart-modal/#/demo](https://biig-io.github.io/ngx-smart-modal/#/demo) , Click on dynamic modal btn, 'Bobby' is a binding value

**Comment by GerkinDev** [comment]
Yes, actually. But it reuses the host component's context, while I'd like to pass an arbitrary object as template context.

**Comment by LouisAugry** [comment]
@maximelafarie What do you think?

**Comment by GerkinDev** [comment]
I found a way of doing what I want using the new examples mentioned above. But I still think setting arbitrary context can be useful.
