### ISSUE TITLE
BrowserModule should be removed

### ISSUE THREAD

**Issue by lmauri** [biig-io/ngx-smart-modal#35]
If I import the NgxSmartModal in my shared module i will get an error saying "BrowserModule has already been loaded. If you need access to common..."

To make it work I have to remove  the BrowserModule and BrowserAnimationModule from the NgxSmartModal decorators in ngx-smart-modal.js

NgxSmartModalModule.decorators = [
    { type: NgModule, args: [{
                declarations: [NgxSmartModalComponent],
                exports: [NgxSmartModalComponent],
                imports: [CommonModule]
            },] },
];

**Comment by maximelafarie** [comment]
@lmauri Thank you for this report. I'll take a look at it asap. I'll firstly check if it won't break anything in project that currently use it.

[Here is the concerned file](https://github.com/biig-io/ngx-smart-modal/blob/master/src/ngx-smart-modal/src/modules/ngx-smart-modal.module.ts).

I'll notice you when it's fixed.

**Comment by maximelafarie** [comment]
Should be fixed by #38 .

**Comment by maximelafarie** [comment]
PR #38 has been merged ! It should solve this issue. Many thanks to @thomascsd! 👍
