### ISSUE TITLE
How to use multiple modal windows in single page

### ISSUE THREAD

**Issue by vasanth1982** [biig-io/ngx-smart-modal#39]
Thanks for sharing code. 
In my code `component.ts` page i have to call 2 model popups in a single page.
I getting error when i hit button I am getting error in console saying "_BodyComponent.html:49 ERROR TypeError: Cannot read property 'modal' of undefined_"
here is my code:
```
1. <button (click)="ngxSmartModalService.getModal('myModal1').open()">Open myModal1</button>
2. <button (click)="ngxSmartModalService.getModal('myModal2').open()">Open myModal2</button>
```
html:
```
<ngx-smart-modal #myModal1 [identifier]="'myModal1'"> 
  <button (click)="myModal.close()">Close</button>
</ngx-smart-modal>

<ngx-smart-modal #myModal2 [identifier]="'myModal2'"> 
<button (click)="myModal.close()">Close</button>
</ngx-smart-modal>
```

In component:
```
ngAfterViewInit() {
    const obj: Object = {
      prop1: 'test',
      prop2: true,
      prop3: [{a: 'a', b: 'b'}, {c: 'c', d: 'd'}],
      prop4: 327652175423
    }; 
    this.ngxSmartModalService.setModalData(obj, 'myModal1');

const obj_one: Object = {
      prop1: 'test2',
      prop2:  'data' 
    }; 
    this.ngxSmartModalService.setModalData(obj_one, 'myModal2');
  }
```

**Comment by vasanth1982** [comment]
Please see below attached image:
![error_modal](https://user-images.githubusercontent.com/32838873/31610489-d94f18ba-b295-11e7-9d70-0fde69807b2d.jpg)

**Comment by vasanth1982** [comment]
![error_modal1](https://user-images.githubusercontent.com/32838873/31610540-10bba50c-b296-11e7-9283-fe31e27e0501.jpg)

**Comment by maximelafarie** [comment]
Firstly, is `ngxSmartModalService` declared as `public` in your `constructor()`?

Secondly, you can try to replace this piece of code:
```
1. <button (click)="ngxSmartModalService.getModal('myModal1').open()">Open myModal1</button>
2. <button (click)="ngxSmartModalService.getModal('myModal2').open()">Open myModal2</button>
```
by:
```
1. <button (click)="myModal1.open()">Open myModal1</button>
2. <button (click)="myModal2.open()">Open myModal2</button>
```
Because `#myModal1` and `myModal2` are direct references to the modal element.

Then in this piece of code:
```
<ngx-smart-modal #myModal1 [identifier]="'myModal1'"> 
  <button (click)="myModal.close()">Close</button>
</ngx-smart-modal>

<ngx-smart-modal #myModal2 [identifier]="'myModal2'"> 
<button (click)="myModal.close()">Close</button>
</ngx-smart-modal>
```

You're doing `(click)="myModal.close()"` but `myModal` seems to be not declared anywhere. So you need to use the modal references I previously mentioned:

```
<ngx-smart-modal #myModal1 [identifier]="'myModal1'"> 
  <button (click)="myModal1.close()">Close</button>
</ngx-smart-modal>

<ngx-smart-modal #myModal2 [identifier]="'myModal2'"> 
<button (click)="myModal2.close()">Close</button>
</ngx-smart-modal>
```
Notice that `myModal1.close()` is a reference to `#myModal1` and not `[identifier]="'myModal1'"` which is a unique identifier for a modal.

Hope this helps. :)

**Comment by maximelafarie** [comment]
P.S.: **do not use snake case** for you variable declaration, prefer camel case. So in your component, `obj_one` becomes `objOne`. 😉

**Comment by vasanth1982** [comment]
1.  `ngxSmartModalService` i declared as public in my constructor()` 
2. After change the below 2 line its working perfect thanks very useful. i am hanging since 3 days using different model window but this `ngx-smar-model` awesome.  

`1. <button (click)="myModal1.open()">Open myModal1</button>
2. <button (click)="myModal2.open()">Open myModal2</button>`

Thank you very mush... :)

**Comment by vasanth1982** [comment]
one final doubt can we use individual `.html` pages for each model popup.. ?

**Comment by maximelafarie** [comment]
@vasanth1982 Thank you very much for the kind words 😉

To answer your last question, yes it's completely possible. You can use one html file per modal. But they have to be component's html files to be included in your Angular app. A standalone html file won't be interpreted by the compiler if it's not a component template.

For example:

**modal-one.component.html:**
```
<ngx-smart-modal #myModal1 [identifier]="'myModal1'"> 
  <button (click)="myModal1.close()">Close</button>
</ngx-smart-modal>
```

**modal-two.component.html:**
```
<ngx-smart-modal #myModal2 [identifier]="'myModal2'"> 
  <button (click)="myModal2.close()">Close</button>
</ngx-smart-modal>
```

Then you can manipulate them wherever in your app! (don't forget to include your components in your `app.module.ts` 😄

**Comment by vasanth1982** [comment]
Thanks and appreciated.

**Comment by sherlileee** [comment]
In Angular 6 project, I have done the same. 
But it  return me error with Cannot read property 'open' of undefined
And I have check the this.ngxSmartModalService , there is nothing in modalStack.

**Comment by khylias** [comment]
Hi @sherlileee ,
can you provide us a [stackblitz](https://stackblitz.com/) ? It'll help us to understand your case.

Besides, I invite you to answer me directly on the [gitter](https://gitter.im/ngx-smart-modal/Lobby?source=all-rooms-list) , it is there to answer support questions such as yours.

**Comment by AmirGilboa** [comment]
same thing here. Angular 6, 
Cannot read property 'open' of undefined
i'm literally copying the example to my project.
will try to put on stackblitz tomorrow.

**Comment by khylias** [comment]
Hi @AmirGilboa ,

can you provide us a [stackblitz](https://stackblitz.com/) ? It'll help us to understand your case.
Besides, we tested the component with Angular 6 and it works fine.

Thanks for your interest about our component 🤘

**Comment by AmirGilboa** [comment]
Here is a simple project on stackblitz that has the same or similar issue as mine: 
ERROR Error: Cannot read property 'modal' of undefined.
[https://stackblitz.com/edit/angular-nlh8lw](url)

Thanks.

**Comment by khylias** [comment]
@AmirGilboa please refer to [#140](https://github.com/biig-io/ngx-smart-modal/issues/140#issuecomment-419817483)
