### ISSUE TITLE
with changeDetection: ChangeDetectionStrategy.OnPush close doesnt close backdrop

### ISSUE THREAD

**Issue by dc-m** [biig-io/ngx-smart-modal#47]
Angular 4.3.3 if you have the component change detection set to onpush the backdrop will not close

**Comment by maximelafarie** [comment]
Thank you for your feedback @dc-m! I take a look at it!

**Comment by dc-m** [comment]
Just to point out - it will close, but I have to click twice!

**Comment by maximelafarie** [comment]
This is a bug with `changeDetection`. I'll try replacing it with `markForCheck`, it may solve this issue.
