### ISSUE TITLE
Error on open : BrowserAnimationModule

### ISSUE THREAD

**Issue by khylias** [biig-io/ngx-smart-modal#50]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
I've got the NPM Warning with web-animation-js, I add it. But it keep an error on modal opening.

`NgxSmartModalComponent.html:64 ERROR Error: Found the synthetic property @dialog. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.`

**Expected behavior**
Integrate BrowserAnimationModule on NgxSmartModalComponent directly.

**Reproduction of the problem**
Install module and try.

* **NgxSmartModal version:** 3.0.0

* **Angular version:** 4.4.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by maximelafarie** [comment]
Thanks for submitting your issue @khylias.

Can you please provide the content of the `*.module.ts` where `NgxSmartModalModule` is imported?

**Comment by khylias** [comment]
My app.module.ts : 

```
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';
import {ThemeModule} from './theme/theme.module';
import {HttpClientModule} from '@angular/common/http';
import {CarouselModule} from 'angular4-carousel';
import { NgxSmartModalModule, NgxSmartModalService } from 'ngx-smart-modal';


import {AppRoutingModule} from './app-routing.module';
import {AppComponent} from './app.component';

import {
	ApplicationService
} from './_services';

@NgModule({
	declarations: [
		AppComponent
	],
	imports: [
		BrowserModule,
		ThemeModule.forRoot(),
		AppRoutingModule,
		HttpClientModule,
		CarouselModule,
		TruncateModule,
		NgxSmartModalModule.forRoot()
	],
	providers: [
		ApplicationService,
		NgxSmartModalService
	],
	bootstrap: [AppComponent]
})
export class AppModule {
}

```


I need to add in module's imports : 
```
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
```

**Comment by maximelafarie** [comment]
Exactly @khylias! You need to import `BrowserAnimationsModule` into your module and the error will be gone :wink:

**Comment by khylias** [comment]
Why not import it in next NgxSmartModule's release ?

**Comment by maximelafarie** [comment]
@khylias I just edited my previous answer to explain it. Sorry :wink:
