### ISSUE TITLE
How to call any component method from ngx-smart-modal view?

### ISSUE THREAD

**Issue by ManishGuptaDev** [biig-io/ngx-smart-modal#69]
Hi @maximelafarie, below is not the actual code but sample code to show what I am trying to achieve. Basically, I want to call child component method from "ngx-smart-modal" view which is in the my-app component. 
(click)="child.doSomething()"

I give child component an Identifier name "#child" and trying to call its method using "child.doSomething()". But it is not working and throwing an error something like that "Cannot read doSomething  of undefined"

Maybe I am doing it in a wrong way so I want to know how to call component methods from "ngx-smart-modal" no matter where this modal is present in my-app application?

```
import {Component} from '@angular/core';
import {NgxSmartModalService} from 'ngx-smart-modal';

@Component({
  selector: 'my-app',
  templateUrl: '<child-cmp #child></child-cmp>
                <ngx-smart-modal #myModal1 [identifier]="'myModal1'"> 
                    <button (click)="child.doSomething()">submit</button>
                </ngx-smart-modal>'
})

export class AppComponent {
  constructor(public ngxSmartModalService: NgxSmartModalService) {
  }
}


@Component({
  selector: 'child-cmp',
  template: '<p>child</p>'
})
class ChildCmp {
  doSomething() {}
}
```

**Comment by maximelafarie** [comment]
Hi @ManishGuptaDev, please can you edit your issue's description and give an example of what you want to do?

**Comment by maximelafarie** [comment]
@ManishGuptaDev I don't know why you can't do that. It's completely possible as I reproduce your example to make it work: **https://stackblitz.com/edit/ngx-smart-modal-example-3hwafz**.

So it's not a library error but more an in-project error. For example verify that your `doSomething()` method is public, etc.

Hope it helps you. Happy coding. 😉
