### ISSUE TITLE
Unable to use custom directives

### ISSUE THREAD

**Issue by VereeckenJamie** [biig-io/ngx-smart-modal#75]
## Expected Behavior
Custom attribute directive to work as intended

## Current Behavior
Directive not working in any way, Not being triggered either.

## Steps to Reproduce
1. Create a custom directive (E.g.: Change background color on input)
2. Put inside `<ngx-smart-modal><ngx-smart-modal/>`
3. Open Modal

## Code example
component.template.html
```
<ngx-smart-modal #userFormModal [identifier]="'user-form-modal'" [backdrop]="false"
                  [customClass]="'form-modal'"
                  [closable]="false">
  <input type="text" appHighlight />
</ngx-smart-modal>
```

Opening modal with

```
constructor(public modalService: NgxSmartModalService){}

openModal(): void {
  this.modalService.getModal('user-form-modal').open();
}
```

highlight.directive.ts

```
import { AfterViewInit, Directive, ElementRef, OnInit } from '@angular/core';

@Directive({
  selector: '[appHighlight]'
})
export class HighlightDirective implements {
  constructor(private el: ElementRef) {
    el.nativeElement.style.backgroundColor = 'yellow';
  }
}
```

**Comment by maximelafarie** [comment]
Can you provide an example of the code you're using?

**Comment by VereeckenJamie** [comment]
Updated initial question

**Comment by maximelafarie** [comment]
First thing I see right now is in your directive : 

You're importing `OnInit` without implementing it:
```
export class HighlightDirective implements {
  constructor(private el: ElementRef) {
    el.nativeElement.style.backgroundColor = 'yellow';
  }
}
```

So it needs to be:
```
export class HighlightDirective implements OnInit {
  constructor(private el: ElementRef) {
    el.nativeElement.style.backgroundColor = 'yellow';
  }
}
```

Just tell me if you missed it while copying the code into the issue or if you really missed it. 😉

**Comment by VereeckenJamie** [comment]
Just missed it during copying. I have the directive tested on another input which is not in the modal. The directive shouldn't be the problem.

**Comment by maximelafarie** [comment]
That is strange. 🤔 In addition to my previous answer, I can tell you that any custom directive will work inside `ngx-smart-modal`. 

Working example here: **https://stackblitz.com/edit/ngx-smart-modal-example-v7gzyx** (feel free to play with it to see how it works and tell me if it solves your issue).

**Comment by VereeckenJamie** [comment]
It's fixed. Seemed to be a combination of a typo (capital instead of lowercase) and some module importing issues. Anyway, thanks for the help!

**Comment by maximelafarie** [comment]
@VereeckenJamie happy to see you could solve your issue. My pleasure, happy coding my friend! 🤓
