### ISSUE TITLE
SetModalData isn't overwritten on dynamic set

### ISSUE THREAD

**Issue by khylias** [biig-io/ngx-smart-modal#81]
**I'm submitting a ...**  (check one with "x")
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter

**Current behavior**

I'll set my modal data dynamically on a click event, but data doesn't change when I'll click on an another button and keep the first data.

**Expected behavior**

All of my modal open with the right data.

**Reproduction of the problem**

You can test my behavior here : https://plnkr.co/Ov124mJajTkWxmrl8hrZ?p=preview

**What is the motivation / use case for changing the behavior?**

I've got dynamic data and I need to set dynamic modal data.

**Please tell us about your environment:**

No need for this issue.

* **Smart Modal version:** 2.0.x

* **Angular version:** 5.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by maximelafarie** [comment]
Thank you @khylias! I'll take a look at it asap 👌

**Comment by maximelafarie** [comment]
Sorry @khylias I didn't realize at the moment, but it has already been planned! The `setModalData()` method has a third optional argument (`boolean`, default to `false`) to override or not potentially existing modal data. 

So in your example, you simply need to call the method like this: `this.modalService.setModalData(dataToPass, 'modal-infos', true);`.

Sorry for misunderstanding, it needs to be in the doc. 

Happy coding! 🖖
