### ISSUE TITLE
[Feature Request] Add dismissable input for modals

### ISSUE THREAD

**Issue by dc-m** [biig-io/ngx-smart-modal#82]
[ ] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter

**Current behavior**
Currently if you click the backdrop the modal closes.

**Expected behavior**
If [dismissable] is false clicking the backdrop doesnt close the modal.

**Reproduction of the problem**
<ngx-smart-modal #myModal [identifier]="'myModal'" [dismissable]="false" [closable]="false" [escapeAble]="false"></ngx-smart-modal>

**What is the motivation / use case for changing the behavior?**
I currently have an upload with file selector on a modal. If i click and select the file from the file selector it closes but if I do an additional click accidentally and it lands on the backdrop it will close the modal.

Having a dismissable false will stop the backdrop from being used as a close

**Comment by dc-m** [comment]
As an additional note - i am currently attemping to use onDismiss to cancel the close event

**Comment by maximelafarie** [comment]
Thank you for reporting this issue @dc-m! I'll take a look at it and let you know when it's implemented. 👌

**Comment by dc-m** [comment]
Currently seeing if I can do this myself on a forked version as onDismiss is emitted after dismissed and i ideally needed a beforeDismiss with an option to cancel the event.

**Comment by maximelafarie** [comment]
Closed by #84. Please use version `5.0.0`. Option's name is `dismissable`. Refer to the docs to get more info. Happy coding 🖖
