### ISSUE TITLE
Issue using angular 4

### ISSUE THREAD

**Issue by cdchn1989** [biig-io/ngx-smart-modal#85]
Hello i using you very good component but have a question when run de command npm start i get this error 
```
ERROR in Error: Metadata version mismatch for module C:/wamp64/www/FMA/app/node_modules/ngx-smart-modal/ngx-smart-modal.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/wamp64/www/FMA/app/src/app/app.module.ts, resolving symbol AppModule in C:/wamp64/www/FMA/app/src/app/app.module.ts, resolving symbol AppModule in C:/wamp64/www/FMA/app/src/app/app.module.ts
    at Error (native)
    at syntaxError (C:\wamp64\www\FMA\app\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\wamp64\www\FMA\app\node_modules\@angular\compiler\bundles\compiler.umd.js:25118:23)
    at StaticReflector.simplify (C:\wamp64\www\FMA\app\node_modules\@angular\compiler\bundles\compiler.umd.js:25130:13)
    at StaticReflector.annotations (C:\wamp64\www\FMA\app\node_modules\@angular\compiler\bundles\compiler.umd.js:24558:41)
    at _getNgModuleMetadata (C:\wamp64\www\FMA\app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\wamp64\www\FMA\app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\wamp64\www\FMA\app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\wamp64\www\FMA\app\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\wamp64\www\FMA\app\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\wamp64\www\FMA\app\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

But if i remove the dependeci injeccion of your module before npm start, this complile ok, if i put the dependencies of your module after to compile (npm start) all is ok. I have no idea what happend

This is my package.json

```
  "name": "fma",
  "version": "3.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@amcharts/amcharts3-angular": "^1.5.0",
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "^2.0.0-beta.11",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.11",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular-datatables": "^4.4.0",
    "core-js": "^2.4.1",
    "datatables.net": "^1.10.16",
    "datatables.net-dt": "^1.10.16",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "ngx-smart-modal": "^5.0.0",
    "ngx-toastr": "^6.4.0",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.3",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/datatables.net": "^1.10.6",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.13",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```

Best regards

**Comment by khylias** [comment]
Hi, 

try to delete your `node-modules` folder and run again `npm start` to cleanup all dependencies.
If this doesn't work, can you put more details of your case in a plunker ?

Have a good day 😉

**Comment by Pescu** [comment]
Same issue here, this error generally is generated when he expect a version on angular higher, for example >5.0, and we use the version <5.0. What is the version you recommend for angular 4?

**Comment by maximelafarie** [comment]
Interesting issue @cdchn1989 and @Pescu... 🤔

Are you facing the same issue with @khylias solution?

You can check the `4.1.0` version out, as this diff shows: https://github.com/biig-io/ngx-smart-modal/commit/aa0f0e00dac1ce3a6ff6ac9e48071060037032a0 (check `package.json` in the library folder).

Tell me if it changes anything for you.
I'll investigate.

**Comment by Pescu** [comment]
I just try with version 4.1.0 and same error, then i tried version 3.1.0 and works.

**Comment by maximelafarie** [comment]
Ok @Pescu but you might loose some functionalities and/or fixes. 
This error seems to be recurrent with libraries that handle Angular 5.x.x used in Angular 4.x.x projects.

Silly question: can't you upgrade your project to Angular 5? 😕 

(e.g. here: https://github.com/KoderLabs/ngx-device-detector/issues/25 or here: https://github.com/angular/material2/issues/8229)

I have to take a look at the `peerDependencies` and do some additional tests on the CI.

**Comment by Pescu** [comment]
@maximelafarie Right now i cannot afford to update to angular 5 seen the many changes that I should do, but i will try to do it in the future. Thanks for the responsiveness of the answer. Cheers!

**Comment by maximelafarie** [comment]
@Pescu I completely understand, it was a silly question! 😋 

You can be assured I'll take a look at it asap and check if I can do anything to make it work for Angular <5.x.x versions 👌 

Stay tuned! 🖖

**Comment by cdchn1989** [comment]
Hi for angular 4 the correct version is 3.1.0 , would be good upgrade to angular 4 or 5 your version 5.0.0

thanks  a lot

**Comment by khylias** [comment]
@cdchn1989 Hi, thanks to found out the optimal version for Angular 4. 
I don't think that making a specific upgrade for angular 4 is a good idea. But we can tell on the README that the best version with Angular 4.x is our 3.1.0 version.

**Comment by maximelafarie** [comment]
Add `wontifx` label since @khylias is clear and `3.1.0` works with Angular `<5.x.x`. Will add an info block about this issue on the README.

@cdchn1989, @Pescu:
We need more info about how to fix this issue, if we have the time we'll look at it deeply. 👌
PRs are highly appreciated! 🤝

**Comment by cdchn1989** [comment]
Yes sure.

Normally i install with npm by the command npm install ngx-smart-modal --save this command works fine but if you use angular 4.x.xyo need the version 3.1.0 of ngx-smart-modal, you need follow the next steps if you use angular-cli:

1. npm uninstall ngx-smart-modal --save
2. npm install ngx-smart-modal@3.1.0 -save

with that is enough to use it with angular 4.x.x

Best Regards

**Comment by maximelafarie** [comment]
Thank you very much @cdchn1989. Your message will be the reference for all potential users that may facing this issue!

Happy coding! 🖖

**Comment by khylias** [comment]
@cdchn1989 Very interesting things ! It seems to be npm or node version who make trouble.

Can you tell us your angular-cli, npm and node versions ?

**Comment by maximelafarie** [comment]
Good point @khylias! Did you try with Yarn instead of NPM @cdchn1989?
E.g.: `yarn add ngx-smart-modal` instead of `npm install ngx-smart-modal --save`

**Comment by mor12** [comment]
i confirm that the correct way is use the version 3.1.0 for angular 4 and version 5.0.0 +  for angular 5

**Comment by madhuri03** [comment]
There is no dismissable option support in version 3.1.0. I need to set it false.
