### ISSUE TITLE
Opening same modal in multiple components

### ISSUE THREAD

**Issue by hectoreft** [biig-io/ngx-smart-modal#92]
Hello,

What i am trying to do is open a modal that has been created in a componentA, in another component called  componentB, in order to use the same modal in multiple Components on click events, but im getting this error:

```
_ERROR TypeError: Cannot read property 'modal' of undefined
    at NgxSmartModalService.getModal (ngx-smart-modal.js:64)
    at Object.eval [as handleEvent] (componentB.html:4)
    at handleEvent (core.js:13547)
    at callWithDebugContext (core.js:15056)
    at Object.debugHandleEvent [as handleEvent] (core.js:14643)
    at dispatchEvent (core.js:9962)
    at eval (core.js:10587)
    at HTMLButtonElement.eval (platform-browser.js:2628)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4740)_
```

 Am I doing something wrong? or how can I acomplish this task?

Here is the code:
**_ComponentA_**

```
<ngx-smart-modal #myModal identifier="myModal" [closable]="true" [escapable]="true" [dismissable]="true">
  <h1>Title</h1>
  <p>Some stuff...</p>

  <button class="btn btn-primary" (click)="myModal .close()">Close</button>
</ngx-smart-modal>

<button class="btn btn-primary" (click)="ngxSmartModalService.getModal('myModal').open()">Open myModa</button>

import { Component, OnInit, AfterViewInit } from '@angular/core';
import { NgxSmartModalService } from 'ngx-smart-modal';


@Component({
  selector: 'app-componentA',
  templateUrl: './componentA.component.html',
  styleUrls: ['./componentA.component.css']
})
export class ComponentA implements AfterViewInit {

  constructor(public ngxSmartModalService: NgxSmartModalService) { }
  ngAfterViewInit() {
    const obj: Object = {
      prop1: 'test',
      prop2: true,
      prop3: [{ a: 'a', b: 'b' }, { c: 'c', d: 'd' }],
      prop4: 327652175423
    };

    this.ngxSmartModalService.setModalData(obj, 'myModal');
  }
}
```

**_ComponentB_**
```
<button class="btn btn-primary" (click)="ngxSmartModalService.getModal('myModal').open()">Open myModa</button>

import { Component, OnInit, AfterViewInit } from '@angular/core';
import { NgxSmartModalService } from 'ngx-smart-modal';

@Component({
  selector: 'app-componentB',
  templateUrl: './componentB.component.html',
  styleUrls: ['./componentB.component.css']
})
export class ComponentB {
  constructor(public ngxSmartModalService: NgxSmartModalService) { }
}
```

**Comment by maximelafarie** [comment]
Hi @hectoreft, 
Firstly, thank you for submitting a well formatted issue! 🙂

Can you tell me what is the relationship between your two components? Are they at the same level? Are they parent/child?

Have your components their own modules or do they share a same module?

**Comment by hectoreft** [comment]
Hi @maximelafarie thanks for your fast answer, 

_**Can you tell me what is the relationship between your two components? Are they at the same level? Are they parent/child?**_
I am new to angular 5, but I will try to explain what I need to do:

The two components has not relationship, they ara at the same level, but both of them need to use the same modal, imagine that i want to open a modal that contains  a employee filter, this modal should contain afew search elements like the name of the employee or the number of the employe, when i click search then i want to pass the data to de component where has been called this modal.

**_Have your components their own modules or do they share a same module?_**
They sare the same module.

Regards

**Comment by maximelafarie** [comment]
With pleasure @hectoreft! 😉 

I understand, but it's hard to help you only with code snippets, could you reproduce your issue on [stackblitz](https://stackblitz.com/) please? You can fork the [following ngx-smart-modal example](https://stackblitz.com/edit/ngx-smart-modal-example) if you want!

**Comment by hectoreft** [comment]
Hi @maximelafarie, 

I already post my issue on stackblitz, this is the url:
https://stackblitz.com/edit/ngx-smart-modal-example-fp1xhv


Tks for your help. :)

**Comment by maximelafarie** [comment]
### Some more infos: 
Assuming the following diagram:
![image](https://user-images.githubusercontent.com/5319267/37738425-439fa8c4-2d57-11e8-9596-ee94779ffe09.png)

Let's say you declare your modal markup into the **Component A** and you want to do some stuff with it (set data, open it and so on...) in the **Component B**.

Then you need to wait the time **Component A** instanciates before doing anything with the modal in **Component B**.

A way to avoid issues like `undefined` is to declare the modal markup in a parent component like that:
![image](https://user-images.githubusercontent.com/5319267/37738818-7fda54dc-2d58-11e8-863e-524298285cbd.png)

⚠️ The above diagrams are only for example purposes, and **do not** reflect the way of importing or using the components between them or with modules.

**Comment by khylias** [comment]
Hi @hectoreft ,

I've took a look on your issue and I find some missing element.
Modal is undefined because it isn't call in your app.

Add to `app.component.ts` this code below : 
```
<app-component-a></app-component-a>
<app-component-b></app-component-b>
<app-modal-component></app-modal-component> <!--- This line is missing --->
```

Hope it'll help ! 
And Thanks to formating your issue with the right template 👏

**Comment by maximelafarie** [comment]
Too fast @khylias.
@hectoreft I forked your fork with @khylias above fix, all works as expected: **https://stackblitz.com/edit/ngx-smart-modal-example-qtt5v9** 👌

**Comment by hectoreft** [comment]
That is exactly what i wanted, it worked perfectly

Tks Guys for your help, I have a few other questions, where can i post them if they are not issues?

**Comment by khylias** [comment]
Yes, open an issue per questions 😉 It would be much easier for us to manage issues.

Enjoy with ngx-smart-modal 🚀

**Comment by maximelafarie** [comment]
Cool @hectoreft!

In addition to what @khylias said, you can also ask **quick** questions on [our Gitter](https://gitter.im/ngx-smart-modal/Lobby).
(but be careful, quick questions, quick answers! 😉)

Happy coding! 🖖
