### ISSUE TITLE
Return Promise on open()

### ISSUE THREAD

**Issue by PendelinP** [biig-io/ngx-smart-modal#98]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
The current open() method does not return any Promise<> which is awaitable.

**Expected behavior**
Promise which can be awaited (resolved via classical way) after the modal has been closed/dismissed. Right now there is now way for prompting the user for something and continue afterwards.

**What is the motivation / use case for changing the behavior?**
I want to wait for the users input within a wizard flow.

* **Smart Modal version:** 6.0.0

**Comment by maximelafarie** [comment]
Hi @PendelinP!

You have an entire [part of the documentation](https://github.com/biig-io/ngx-smart-modal#handle-events) dedicated to the different available `Events` on `open / close / dismiss / escape` and so on.

You can use these `Events` as `Promise / Observable`. The advantage is that you can `subscribe / unsubscribe` to them across your app. 

Let me know if it solves your issue ! 😉

**Comment by PendelinP** [comment]
Oh boy - how awkward is that. I read the section a couple of times but totally missed the interesting part :/

You're totally right! Sorry for my issue ;)

...and thanks for the fast response! It works like a charm now :)
