### ISSUE TITLE
NPM documentation out of date

### ISSUE THREAD

**Issue by danieka** [biig-io/ngx-smart-modal#99]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

The installation instruction on NPM under the header appears to be out of date. The line for importing the SCSS is: `@import "ngx-smart-modal/ngx-smart-modal";`. For me this did not work and the line appears to be missing a tilde.

**Expected behavior**

When looking at the documentation on Github that line on how to importing SCSS is `@import "~ngx-smart-modal/ngx-smart-modal";`. Here a tilde appears in the path, and this import path works for me.

**Suggested solution**

Update the NPM page https://www.npmjs.com/package/ngx-smart-modal to have the correct import path for scss.

**Comment by maximelafarie** [comment]
Thank you for reporting this issue @danieka. 
Indeed, the documentation about styles is up to date in the [GitHub repo doc](https://github.com/biig-io/ngx-smart-modal#style--customization) but not on NPM.

The readme on NPM needs to be updated. I'll do it asap. 😉 

Happy coding! 🖖
